### ISSUE TITLE
infinite loop when trying to create account

### ISSUE THREAD

**Issue by dhruvrana72** [adjoint-io/uplink-explorer#74]
When I am initiating a new chain with new node, it is showing old blocks, in earlier versions it use to start a new chain. And when I am trying to create a new account, it 's going into infinite loop.

Here's the link to screencast:
https://drive.google.com/file/d/18XEnjZgghSquDvnuOmoAuDJzxEDculXy/view?usp=sharing

**Comment by tdietert** [comment]
I can explain the first issue regarding "old" blocks:

In version 1.1 of Uplink, we have changed the way you initialize/run a node using an existing database. Currently the config file you are using has `storage.backed = leveldb:///uplink` which means that the node is going to look for a database in the `<currentWorkingDirectory>/uplink` directory, and if it doesn't find one, it will create one there. In your case, you are not changing this field nor overriding it on the command line, so the node is looking for a database in the `uplink` directory and finding one (the one created by the previous node, along with the 40 blocks created by it). In order to tell the new node to create a database in a _different_ database please run:

`uplink chain init -d node123 -b "leveldb:///uplink1" -c node.config.local -k config/validators/auth0/key`

or modify the `storage.backend` field in the config file you are using to use a different directory than the previous node for storing node specific data files.

Also, we have changed the `-d` flag to refer to the directory in which the node is going to store its "database agnostic" data, like it's JSON serialize account, it PEM serialize public and private keys, it's peers, etc. You will need to alter the node data directory either via command line (changing the `-d node123` to a directory that was not used by the previous node) or by modifying the `storage.directory` field in the config file.

---

I am not sure why the `CreateAccount` transaction you are issuing is not being included in block 40. As first steps I would say to make sure you are using the latest version of the block explorer and uplink SDK. It doesn't look like the uplink node is logging an error which is should if the transaction is invalid and being discarded as the node scans the mempool before it constructs a block.

Try fixing the first issue, and then try to issue another `CreateAccount` transaction the same way and see if you have the same issue.

**Comment by dhruvrana72** [comment]
Hello,
I tried changing the database like you mentioned, It did showed creating a new database. But still creating account is giving me same error.
I even tried re-installing everything from the start. Using [this](https://github.com/adjoint-io/uplink) release of uplink and [this](https://github.com/adjoint-io/uplink-explorer) release of uplink-explorer.

link to screen cast: https://drive.google.com/file/d/19mAQvI3aS4yDLMSHJL0HWbwCycEBbbVe/view?usp=sharing

**Comment by dhruvrana72** [comment]
I tried creating account using python console. I think what is happening is RPC is not returning any response for the transaction and hence, uplink-explorer is waiting for the response.

**Comment by tdietert** [comment]
I have tried to recreate the issue locally, but could not. Could you please run the node in verbose mode and check the stdout logging of the uplink node? "verbose" can be activated by passing a `-v` flag to the `uplink` command.

**Comment by dhruvrana72** [comment]
Nothing unusual in the output. RPC response is also there.

Here's the link:
https://drive.google.com/file/d/1VOnPA4Pk03xNjZBNITL_yBXf-N5-f1AY/view?usp=sharing

**Comment by dhruvrana72** [comment]
update2: After 5 minutes the block creation took place and the loading stopped.

**Comment by dhruvrana72** [comment]
```
[2017-12-07 15:36:19 IST : INFO] Recieved Cmd from RPC:
	Transaction (Transaction {header = TxAccount (CreateAccount {pubKey = "48ad6632e26bfc23e6b5a1d3b8b6b89ba3eadfbe29ad55c3a2cb3783b0abb7152b7f1f849d9c699a3242fd661a8428d02ff1d4aaabb85d48018e7da3f6bcce0a", timezone = "GMT", metadata = Metadata {unMetadata = fromList []}}), signature = "AE0zNzcyOTQ4Mzg2NzY5Njg2MTAyMDMxMDY1NDgwMzQ0MDYyMjYzMDA3MTM0NjcwMjUyNTY4MzIxNDU5ODIwNDU1OTUxOTI0OTYwMDQ0MToATTk3OTYzMDA0MTg5MzE2NjY3MjY2NjY2ODU1ODk0Njk3MDU3OTQwMDI4MzA2MTY1Njg5NTMyNjY2NTk4MzIwODIyOTc1NDI1NzQ1NTUy", origin = TxpChgSxdWCE7rc9ZeVaipEr8VBKM7q2ETuENosNNJX, timestamp = 1512641179753345})
```



```
[2017-12-07 15:40:25 IST : INFO] Recieved Message: 
	Block (BlockMsg {block = Block {index = 6, header = BlockHeader {origin = F8XUEiSUDKRhG6Srfft7zB4n8KWEZ6G3YnRg3F5MetVU, prevHash = "5587783047b6a358536662bfb9219081e8963e2242d02210e4031a7d36ef6710", merkleRoot = "ca6e525a9e4c0296c279958e1ec68175afca177991e97395596881c07ad5130a", timestamp = 1512641425249084, consensus = PoA {validatorSet = ValidatorSet {unValidatorSet = fromList [32zr5nyqWfguKBWEWW6SbB9NnciR8yU9rTz4sRwRmK4S,4nn4beQTAT1vo44GDWq97KARVtAg5kN6iDctyPhDnUbv,74Zh9ieinY2fozrvX8cMK2x3hqgP3oXLnCbCceuQZFDY,7fpCnRDgm8B4VdjRk1jvskhNoAPbZ4S5eMD2TF8sytWF,BHAZvsLnFgvmYkaJQpQwcZZAALFxxqttKQtqompDb426,E1qLYBKYgNJerohFhGuBC7q2kBQ7sVGRopn6gNwaBqQf,F8XUEiSUDKRhG6Srfft7zB4n8KWEZ6G3YnRg3F5MetVU,H8L7BGsbLZVkCytBC35SA6FesTP1Y1b8neydvVQ4FY7h,Hocqmrjip3MwyGuTXhfQpUPMhpMZkapo6DnWUDtuuVfu,HyP48is6eiQP1QURvvbVhAFABpP3FKPskFy4qdDCgjKh,vLKc7J2aZEsXzRnxAcZ7tw2kRKKr69ffzTDjRU5fpRh]}, blockPeriod = 1, blockGenLimit = 1, threshold = 1, minTxs = 1, signerLimit = 1}}, signatures = fromList [BlockSignature {signature = Signature {sign_r = 4401679360543330830117045389416730914349995500136214684274869961708371631522, sign_s = 5455025827977957103850274050793653469016346154400218961402894312318150400865}, signerAddr = F8XUEiSUDKRhG6Srfft7zB4n8KWEZ6G3YnRg3F5MetVU}], transactions = [Transaction {header = TxAccount (CreateAccount {pubKey = "48ad6632e26bfc23e6b5a1d3b8b6b89ba3eadfbe29ad55c3a2cb3783b0abb7152b7f1f849d9c699a3242fd661a8428d02ff1d4aaabb85d48018e7da3f6bcce0a", timezone = "GMT", metadata = Metadata {unMetadata = fromList []}}), signature = "AE0zNzcyOTQ4Mzg2NzY5Njg2MTAyMDMxMDY1NDgwMzQ0MDYyMjYzMDA3MTM0NjcwMjUyNTY4MzIxNDU5ODIwNDU1OTUxOTI0OTYwMDQ0MToATTk3OTYzMDA0MTg5MzE2NjY3MjY2NjY2ODU1ODk0Njk3MDU3OTQwMDI4MzA2MTY1Njg5NTMyNjY2NTk4MzIwODIyOTc1NDI1NzQ1NTUy", origin = TxpChgSxdWCE7rc9ZeVaipEr8VBKM7q2ETuENosNNJX, timestamp = 1512641179753345}]}, sender = "127.0.1.1:8001"})
[2017-12-07 15:40:25 IST : INFO] Verifying and Validating block before acceptance...
[2017-12-07 15:40:25 IST : INFO] Applying transactions of block 6 to world state...
[2017-12-07 15:40:25 IST : INFO] Recieved Message: 
```

If you pay attention to time, you can see it took around 4 minutes to create the new block and this happens every time, I start uplink.

**Comment by tdietert** [comment]
Thanks, I have been able to reproduce the issue and am working to diagnose now.

**Comment by dhruvrana72** [comment]
Okay thank you.
Can you please write what was the exact issue with solution, when you'll answer?
Thank will be really helpful.

**Comment by tdietert** [comment]
Ok, so the issue is that the bootnodes listed in the `node.config` file are the IP:Port strings (registered process ids) of our testnet bootnodes. Your local node was querying these node process ids instead of looking at the local network for a process `127.0.0.1:8001`, the ip:port string that identifies itself as one of the boot nodes; there for, the node's own processes were unable to discover themselves (the process that receives the transaction from the RPC server was not sending the transaction to the messaging process because the peer controller hadn't discovered _itself_ yet). Running `uplink` using the local network config file via the `-c config/node.config.local` command line flag should fix your issues.   

Apologies for our documentation that is lacking some of these things. Today and/or tomorrow we are going to do a documentation sprint so that these issues can be resolved more quickly, or not happen at all.

**Comment by dhruvrana72** [comment]
Okay thanks it solved the issue. What are those ip addresses in node.config ? 

```
 "10.132.0.2:8001"
    , "10.132.0.4:8001"
```

Just curious, why you decided to put them there ?

**Comment by tdietert** [comment]
> Ok, so the issue is that the bootnodes listed in the node.config file are the IP:Port strings (registered process ids) of our **testnet bootnodes.**

There is a distinction between `config/node.config` which is generally used in non-local networks, and `config/node.config.local` which is generally used for local networks. This was used as more of a convenience during development, and I can see how it may be confusing, _especially_ when it uses `config/node.config` as the default config file. For your case, i would copy the bootnode IPs from `node.config.local` to `node.config` such that you don't always have to specify the config file via the command line when running uplink. Sorry that this took up quite a bit of your time!

**Comment by dhruvrana72** [comment]
Thanks for explanation. No issue. Thanks alot for help and resolving it.
